spring:
  application:
    name: osio-gateway
  main:
    #因为Gateway不支持SpringMVC，所以要么加上这个配置，要么pom.xml注释掉spring-boot-starter-web
    #web-application-type: reactive
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          my-client:
            client-id: my-client
            client-secret: my-secret
            authorization-grant-type: authorization_code
            #redirect-uri: http://osio-api-dev.lgfei.com/login/oauth2/code/my-client
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
            provider: spring-authorization-server
        provider:
          spring-authorization-server:
            authorization-uri: http://osio-auth-dev.lgfei.com/oauth2/authorize
            token-uri: http://osio-auth-dev.lgfei.com/oauth2/token
            jwk-set-uri: http://osio-auth-dev.lgfei.com/oauth2/jwks
            issuer-uri: http://osio-auth-dev.lgfei.com
            user-info-uri: http://osio-auth-dev.lgfei.com/userinfo
            user-name-attribute: sub
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=Access-Control-Allow-Origin, *
        #- DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
        - PreserveHostHeader
        - TokenRelay
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            #allowedOrigins: "*"
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
        add-to-simple-url-handler-mapping: true
      routes:
        # /admin
        - id: osio-admin
          uri: lb://osio-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        # /auth
        #- id: osio-auth
        #  uri: lb://osio-auth
        #  predicates:
        #    - Path=/auth/**
        #  filters:
        #    - StripPrefix=1
        # /iam
        - id: osio-iam
          uri: lb://osio-iam
          predicates:
            - Path=/iam/**
          filters:
            - StripPrefix=1
        # /file
        - id: osio-file
          uri: lb://osio-file
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1
  data:
    redis:
      host: 10.10.219.168
      port: 6379
      #password: 123456
      database: 1
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 8
          min-idle: 0


osio:
  gateway-url: http://osio-api-dev.lgfei.com