spring:
  application:
    name: osio-auth
  thymeleaf:
    cache: false
    prefix: classpath:/static/pages/
    encoding: UTF-8
    suffix: .html
    mode: HTML

osio:
  gateway-url: http://osio-api-dev.lgfei.com
  route-path: /auth

