spring:
  application:
    name: osio-auth
  thymeleaf:
    cache: false
    prefix: classpath:/static/pages/
    encoding: UTF-8
    suffix: .html
    mode: HTML
  security:
    oauth2:
      authorizationserver:
        issuer: http://osio-auth-dev.lgfei.com
#        client:
#          my-client:
#            registration:
#              client-id: "my-client"
#              client-secret: "{noop}my-secret"
#              client-authentication-methods:
#                - "client_secret_basic"
#              authorization-grant-types:
#                - "authorization_code"
#                - "refresh_token"
#                - "client_credentials"
#              redirect-uris:
#                - "http://osio-api-dev.lgfei.com/login/oauth2/code/my-client"
#              scopes:
#                - "openid"
#            require-authorization-consent: true


osio:
  gateway-url: http://osio-api-dev.lgfei.com
  route-path: /auth

