logging:
  level:
    root: info
    com:
      netflix:
        discovery: error
    org:
      springframework:
        web: warn
        security: trace
        ldap: trace
        security.authentication: trace
        security.ldap: trace