spring:
  application:
    name: osio-file
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://osio-auth-dev.lgfei.com
          jwk-set-uri: http://osio-auth-dev.lgfei.com/oauth2/jwks

example:
  what: osio file service is working